# base - .github/workflows/publish.yml - beg
# Publishing packages to npm and GitHub Packages
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
name: publish
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:


  publish_github:
    name: Publish Package to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          # scope: "@octocat"
      # Publish to GitHub Packages
      - run: sh jslint_ci.sh shCiPublishNpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_REGISTRY: github


  publish_npmjs:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      # Publish to npmjs Packages
      - run: sh jslint_ci.sh shCiPublishNpm
# base - .github/workflows/publish.yml - end
