# this workflow will run nodejs coverages and tests and
# upload build-artifacts to branch-gh-pages
name: CI
on:
  push:
    branches:
      - alpha
      - beta
      - master
      - sandbox
# shCiBase - start
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          - 12
          - 14
          - 16
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    name: node . v${{ matrix.node_version }} . ${{ matrix.architecture }} . ${{ matrix.os }}
    steps:
      # disable autocrlf in windows
      - run: git config --global core.autocrlf false
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      # fetch ci.sh from trusted source
      - run: git fetch origin alpha && git checkout origin/alpha ci.sh
      # run nodejs coverages and tests
      - run: sh ci.sh shCiBase
# shCiBase - end
      # fetch ci.sh from trusted source
      - run: git fetch origin alpha && git checkout origin/alpha ci.sh
      # upload build-artifacts to branch-gh-pages
      - run: sh ci.sh shCiArtifactUpload
        env:
          CI_NODE_VERSION_ARCH_PLATFORM: v14.x64.linux
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
